In [2]:
import numpy as np

In [4]:
mylist = [1,2,3]
type(mylist)

list

In [6]:
myarray = np.array(mylist)
myarray

array([1, 2, 3])

In [7]:
type(myarray)

numpy.ndarray

In [13]:
np.arange(0,10,2) #first parameter is starting point of arraaye and the second para is stoping point of array and the
#third is optional for skip that particular number

array([0, 2, 4, 6, 8])

In [14]:
np.zeros(shape=(5,5)) # for 2d array 

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
np.ones((2,3))  

array([[1., 1., 1.],
       [1., 1., 1.]])

In [50]:
np.random.seed(101)
arr = np.random.randint(0,100,10)

In [51]:
arr

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [57]:
arr2 = np.random.randint(0,100,10)

In [58]:
arr2

array([76, 95, 87,  0, 73,  8, 62, 36, 83, 99])

In [65]:
print(arr.max())#give max of that array
print(arr.argmax())# give max number index of that array
print(arr.min())#give min of that array
print(arr.argmin())# give min number index of that array

95
0
9
7


In [66]:
arr.mean()# mean of that array

60.8

In [68]:
arr.shape

(10,)

In [71]:
arr.reshape((2,5))

array([[95, 11, 81, 70, 63],
       [87, 75,  9, 77, 40]])

In [72]:
matrix = np.arange(0,100).reshape((10,10))

In [76]:
print(matrix)
matrix.shape

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


(10, 10)

In [78]:
row = 4
col = 6

In [79]:
matrix[row,col]

46

In [84]:
matrix[:,1] #give back whole column

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [85]:
matrix[:,1].reshape((10,1))

array([[ 1],
       [11],
       [21],
       [31],
       [41],
       [51],
       [61],
       [71],
       [81],
       [91]])

In [86]:
matrix[1,:] #give back the row of the matrix

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [89]:
matrix[0:3,0:3]# it grab rows and column according to the input

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22]])

In [91]:
mynewmat = matrix.copy()

In [92]:
mynewmat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [93]:
mynewmat[0:6,:]=0

In [94]:
mynewmat

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])